### ISSUE TITLE
Great work thanks! Question regarding new pool

### ISSUE THREAD

**Issue by AndoKarim** [fdundjer/solana-sniper-bot#1]
Hi, from my understanding, you set a listener for each time a new pool is created. 
Is there a way to get the opening time of the pool? 
Could not find the information clearly on Raydium SDK. 

I could help adding this feature to your code.

Regards.

**Comment by fdundjer** [comment]
Hey @AndoKarim, the liquidity pool should be open as soon as it gets created. 
Do you see any errors when running the script?

**Comment by AndoKarim** [comment]
It's just that sometimes a pool can be created but the open_time is in the
future. And for those ones you cannot snipe them since the event is
received and won't be re-triggered when the pool opens.

**Comment by fdundjer** [comment]
Thanks for sharing, I was not aware of this functionality. Looks like pool opening time is available in a new version of Raydium SDK.
https://github.com/raydium-io/raydium-sdk/commit/9d346fcc76d354c8dc2d8c2378131ef3b9fda372
LIQUIDITY_STATE_LAYOUT_V4 now contains pool time.

I think updating SDK package should give you the ability to read the opening time.

**Comment by chiochocolate** [comment]
Hey @AndoKarim , Great question!.

Can i contact you on another platform like instagram or gmail? I have a question about this. Im facing a problem with the opening time.

Thank you,

**Comment by AndoKarim** [comment]
@fdundjer Thanks for your help. 

I tried so far but using LiquidityPoolJsonInfo, it does not have the openingTime on it, even on last version. Pretty weird.

**Comment by dtmrc** [comment]
> @fdundjer Thanks for your help.
> 
> I tried so far but using LiquidityPoolJsonInfo, it does not have the openingTime on it, even on last version. Pretty weird.

i think you have to parse data account using layout_v5..

**Comment by saurabh41** [comment]
is it possible to find pool id from mint address(aka token address) ?

**Comment by fdundjer** [comment]
> @fdundjer Thanks for your help.
> 
> I tried so far but using LiquidityPoolJsonInfo, it does not have the openingTime on it, even on last version. Pretty weird.

Not sure where is the problem, I'm able to get pool time. I'll push the updated version with typed variables, so you can easily find pool time.

ps. If you want just to snipe open pools, instead of checking pool time, you could update the listener to subscribe to the correct pool status.
eg:

```
 {
        memcmp: {
          offset: LIQUIDITY_STATE_LAYOUT_V4.offsetOf('status'),
          bytes: binary_to_base58([1,0,0,0,0,0,0,0])
        },
 }
  ```
  where bytes would in this case represent "Initalized" pool status. You can use 6 instead of 1 to listen to pools that have transitioned from closed (waitingToTrade) to open.
  
Here you can see code that does this transition on raydium: https://github.com/raydium-io/raydium-amm/blob/f290430a417569c3de514c43a17dad872ead59a2/program/src/processor.rs#L1208
 
 If you are not in a rush, I'll update the script.

**Comment by fdundjer** [comment]
@AndoKarim Hey, you can send me a message on discord: ovidije

**Comment by fdundjer** [comment]
@AndoKarim I've added a check for open pools. Let me know if script works as expected.
